#!/usr/bin/env bash

set -eou pipefail

# check_password - Check a pass entry against pwnedpasswords.com.
#
# Takes in a pass entry and outputs the entries
# tested and any compromises to stderr.

echo "Check password: "
read -s PASSWORD
sha1=$(echo -n "${PASSWORD}" | shasum | tr '[:lower:]' '[:upper:]' | awk -F' ' '{ print $1 }')
short=${sha1:0:5}

#echo "${sha1} | ${entry}"
resp=$(curl -s -X GET https://api.pwnedpasswords.com/range/${short})

# Compare local hash against the ones we got from pwnedpasswords.com.
for h in $resp; do
	cleaned_hash=$(echo "${short}${h}" | awk -F: '{ print $1 }')

	if [[ "${cleaned_hash}" == ${sha1} ]]; then
		(>&2 echo -e "\nYour password has been compromised!\n")
	fi
done